// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZuTmPMvZIfPwn4-s57X0I7zGSxBKiYMo',
    appId: '1:898195697004:web:324f7ed83c0e6fc63d1749',
    messagingSenderId: '898195697004',
    projectId: 'todo-manager-2f46a',
    authDomain: 'todo-manager-2f46a.firebaseapp.com',
    storageBucket: 'todo-manager-2f46a.appspot.com',
    measurementId: 'G-MYQ23D0X6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVcHgvU9yh4oV8olVXDWCEJcnQfDFhTIw',
    appId: '1:898195697004:android:f5909fe970e0bc303d1749',
    messagingSenderId: '898195697004',
    projectId: 'todo-manager-2f46a',
    storageBucket: 'todo-manager-2f46a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOwgkTXJvnaXGE8z6dZYs-VwTp8QUNzLU',
    appId: '1:898195697004:ios:9080dcdd2ae3dce23d1749',
    messagingSenderId: '898195697004',
    projectId: 'todo-manager-2f46a',
    storageBucket: 'todo-manager-2f46a.appspot.com',
    iosClientId: '898195697004-slls22j4a43hg3vj2amhmq63o2rfnafp.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoManager',
  );
}
